// Extension catalog; generated/maintained with Docs/Architecture/MMO_Content_Catalog.json.
PROJECTJ_FEATURE("Foundation.Identity", "안정 식별자", "Foundation", "Service", "")
PROJECTJ_FEATURE("Foundation.Access", "권한·소유권 검증 계약", "Foundation", "Service", "Foundation.Identity")
PROJECTJ_FEATURE("Foundation.Persistence", "버전·저장 계약", "Foundation", "Service", "Foundation.Identity")
PROJECTJ_FEATURE("Foundation.Commands", "요청 수명·소유 단위 조정", "Foundation", "Service", "Foundation.Access")
PROJECTJ_FEATURE("Foundation.Events", "이벤트·중복 소비 계약", "Foundation", "Service", "Foundation.Identity")
PROJECTJ_FEATURE("Foundation.Clock", "서버 시간·리셋 기준", "Foundation", "Service", "")
PROJECTJ_FEATURE("Foundation.Transport", "외부 서비스 연결 계약", "Foundation", "Service", "Foundation.Commands")
PROJECTJ_FEATURE("Foundation.Observability", "계측·운영 추적", "Foundation", "Service", "Foundation.Identity")
PROJECTJ_FEATURE("Identity.Account", "계정 프로필", "Identity", "Account", "Foundation.Access,Foundation.Persistence")
PROJECTJ_FEATURE("Identity.Characters", "캐릭터 슬롯·생성", "Identity", "Account", "Foundation.Access,Foundation.Persistence")
PROJECTJ_FEATURE("Identity.Roster", "계정 공유 성장", "Identity", "Account", "Foundation.Access,Foundation.Persistence")
PROJECTJ_FEATURE("Identity.Entitlements", "이용 권한", "Identity", "Account", "Foundation.Access,Foundation.Persistence")
PROJECTJ_FEATURE("Identity.Session", "접속 세션·재접속", "Identity", "Account", "Foundation.Access,Foundation.Persistence")
PROJECTJ_FEATURE("Identity.Appearance", "외형·이름 변경", "Identity", "Account", "Foundation.Access,Foundation.Persistence")
PROJECTJ_FEATURE("Identity.Preferences", "계정 설정", "Identity", "Account", "Foundation.Access,Foundation.Persistence")
PROJECTJ_FEATURE("Identity.Returnee", "복귀 지원", "Identity", "Account", "Foundation.Access,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Inventory", "인벤토리", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Equipment", "장비 장착", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Storage", "창고", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Loot", "드롭·획득 권리", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Enhancement", "강화·실패 누적", "Items", "Character", "Foundation.Commands,Foundation.Persistence,Economy.Wallet")
PROJECTJ_FEATURE("Items.Durability", "내구도·수리", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Sockets", "보석·각인", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Affixes", "옵션 재설정", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Binding", "귀속·거래 제한", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Salvage", "분해·추출", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Loadouts", "장비 프리셋", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Items.Expiration", "기간제 아이템", "Items", "Character", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Economy.Wallet", "재화·원장", "Economy", "Account", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Economy.Vendor", "상점 구매·판매", "Economy", "Account", "Foundation.Commands,Foundation.Persistence,Economy.Wallet,Items.Inventory")
PROJECTJ_FEATURE("Economy.Trade", "개인 거래", "Economy", "Account", "Foundation.Commands,Foundation.Persistence,Economy.Escrow,Items.Binding")
PROJECTJ_FEATURE("Economy.Market", "거래소·경매", "Economy", "Account", "Foundation.Commands,Foundation.Persistence,Economy.Escrow,Items.Binding")
PROJECTJ_FEATURE("Economy.Mail", "우편·첨부 수령", "Economy", "Account", "Foundation.Commands,Foundation.Persistence,Economy.RewardClaims,Items.Inventory")
PROJECTJ_FEATURE("Economy.Escrow", "대금·아이템 보관", "Economy", "Account", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Economy.BuyOrders", "구매 예약", "Economy", "Account", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Economy.Taxes", "수수료·세금", "Economy", "Account", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Economy.Buyback", "재구매", "Economy", "Account", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Economy.CraftingOrders", "제작 의뢰", "Economy", "Account", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Economy.RewardClaims", "보상 수령", "Economy", "Account", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Economy.Gift", "선물·수신 제한", "Economy", "Account", "Foundation.Commands,Foundation.Persistence")
PROJECTJ_FEATURE("Social.Party", "파티", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.RaidGroup", "공격대 편성", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.Guild", "길드·역할·권한", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.Alliance", "길드 연합", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.Friends", "친구·접속 상태", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.Blocklist", "차단·무시", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.Invitations", "초대·수락", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.Recruitment", "모집·지원", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.GuildBank", "길드 창고", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events,Social.Guild,Items.Storage")
PROJECTJ_FEATURE("Social.GuildProjects", "길드 연구·공동 목표", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.Mentorship", "멘토·사제", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Social.Relationships", "유저 관계", "Social", "Group", "Foundation.Access,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Combat.Abilities", "스킬·자원", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Damage", "피해·치유", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Status", "상태 이상·면역", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Threat", "위협도·어그로", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Death", "사망·부활", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Assist", "기여도·지원 판정", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Rulesets", "전투 규칙 세트", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Duels", "결투", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Training", "훈련장·허수아비", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Combat.Spectator", "관전", "Combat", "World", "Foundation.Access,Foundation.Events")
PROJECTJ_FEATURE("Progression.Experience", "레벨·경험치", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Talents", "특성·스킬 트리", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Classes", "전직·전문화", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Quests", "분기·연속 퀘스트", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Objectives", "목표 진행", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Achievements", "업적", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Reputation", "평판·세력", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Unlocks", "콘텐츠 해금", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Codex", "지식·도감", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.AccountMilestones", "계정 공유 업적", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Progression.Catchup", "후발 주자 성장 보정", "Progression", "Character", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("PvE.Dungeons", "던전", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.Raids", "레이드", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.WorldBosses", "월드 보스", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.PublicEvents", "공개 협동 이벤트", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.SoloInstances", "솔로 인스턴스", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.Scaling", "인원·레벨 스케일링", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.Affixes", "주간 변형 규칙", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.Lockouts", "입장·보상 귀속", "PvE", "World", "Combat.Rulesets,Foundation.Clock,Foundation.Persistence")
PROJECTJ_FEATURE("PvE.Challenges", "도전·시간 제한", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.CompanionSupport", "NPC 파티 지원", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvE.Hunting", "현상 수배·사냥 의뢰", "PvE", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.Arena", "투기장", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.Battlegrounds", "전장", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.OpenWorld", "필드 PvP", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.Siege", "공성전", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.Territory", "영토·거점 점령", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.GuildWars", "길드 전쟁", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.Matchmaking", "매칭·대기열", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.Rating", "레이팅·랭킹", "PvP", "World", "Combat.Rulesets,Foundation.Clock,Foundation.Persistence")
PROJECTJ_FEATURE("PvP.Seasons", "경쟁 시즌", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.Tournaments", "대회·대진", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.Crime", "범죄·성향·현상금", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("PvP.FactionCampaign", "진영 공동 전쟁", "PvP", "World", "Combat.Rulesets,Foundation.Clock")
PROJECTJ_FEATURE("Crafting.Recipes", "제작법·숙련도", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Crafting.Processing", "가공", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Crafting.Cooking", "요리", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Crafting.Alchemy", "연금", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Crafting.Quality", "품질·부산물", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Crafting.Research", "연구·발견", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Crafting.Stations", "제작대·시설", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Crafting.Queues", "제작 예약", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Crafting.Specialization", "생산 전문화", "Crafting", "Character", "Items.Inventory,Foundation.Persistence")
PROJECTJ_FEATURE("Life.Gathering", "채집", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Mining", "채광", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Logging", "벌목", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Fishing", "낚시", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Hunting", "수렵", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Farming", "농사", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Breeding", "교배·육성", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Trading", "무역·운송", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Workers", "일꾼·노드 생산", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Sailing", "항해·물물교환", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("Life.Archaeology", "고고학·발굴", "Life", "Character", "Items.Inventory,Foundation.Clock")
PROJECTJ_FEATURE("World.Zones", "지역·채널", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.Instances", "인스턴스 수명", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.Weather", "날씨·환경", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.DayNight", "낮밤·시간", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.Spawns", "스폰·자원 재생", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.Phasing", "퀘스트 위상", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.Discovery", "탐험·지도 해금", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.DynamicEvents", "동적 월드 이벤트", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.Hazards", "지역 위험·환경 효과", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.Interaction", "상호작용·사용 권리", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("World.PublicObjectives", "서버 공동 목표", "World", "World", "Foundation.Events,Foundation.Clock")
PROJECTJ_FEATURE("Travel.Mounts", "탈것", "Travel", "Character", "World.Zones,Foundation.Access")
PROJECTJ_FEATURE("Travel.Vehicles", "다인승 차량", "Travel", "Character", "World.Zones,Foundation.Access")
PROJECTJ_FEATURE("Travel.Ships", "선박", "Travel", "Character", "World.Zones,Foundation.Access")
PROJECTJ_FEATURE("Travel.Stable", "마구간·보관", "Travel", "Character", "World.Zones,Foundation.Access")
PROJECTJ_FEATURE("Travel.Routes", "자동 이동·교통편", "Travel", "Character", "World.Zones,Foundation.Access")
PROJECTJ_FEATURE("Travel.Teleport", "순간이동·귀환", "Travel", "Character", "World.Zones,Foundation.Access")
PROJECTJ_FEATURE("Travel.FastTravel", "거점 이동", "Travel", "Character", "World.Zones,Foundation.Access")
PROJECTJ_FEATURE("Travel.Handover", "서버·채널 이동", "Travel", "Character", "World.Zones,Foundation.Access,Platform.Routing")
PROJECTJ_FEATURE("Travel.Passengers", "탑승자·좌석 권한", "Travel", "Character", "World.Zones,Foundation.Access")
PROJECTJ_FEATURE("Housing.Homes", "개인 주거", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Housing.GuildHalls", "길드 거점", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Housing.Neighborhood", "주거 구역", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Housing.Placement", "가구 배치·충돌", "Housing", "Account", "Foundation.Persistence,Foundation.Access,Housing.Permissions")
PROJECTJ_FEATURE("Housing.Permissions", "방문·편집 권한", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Housing.Plots", "토지·임대", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Housing.Decor", "장식 수집", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Housing.Facilities", "주거 생산 시설", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Housing.Blueprints", "배치 설계도", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Housing.Islands", "개인 섬·영지", "Housing", "Account", "Foundation.Persistence,Foundation.Access")
PROJECTJ_FEATURE("Collections.Wardrobe", "외형 수집", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.Transmog", "형상 변환·염색", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.Pets", "애완동물 수집", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.MountJournal", "탈것 도감", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.Titles", "칭호", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.Emotes", "감정 표현", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.Music", "악보·연주", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.Toys", "장난감", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.Treasures", "보물·희귀 수집", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Collections.PhotoAlbum", "사진·전시", "Collections", "Account", "Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Companions.Pets", "펫 행동·획득 보조", "Companions", "Character", "Foundation.Persistence,Combat.Rulesets")
PROJECTJ_FEATURE("Companions.Mercenaries", "용병", "Companions", "Character", "Foundation.Persistence,Combat.Rulesets")
PROJECTJ_FEATURE("Companions.Training", "동료 육성", "Companions", "Character", "Foundation.Persistence,Combat.Rulesets")
PROJECTJ_FEATURE("Companions.Commands", "동료 명령", "Companions", "Character", "Foundation.Persistence,Combat.Rulesets")
PROJECTJ_FEATURE("Companions.Bond", "친밀도", "Companions", "Character", "Foundation.Persistence,Combat.Rulesets")
PROJECTJ_FEATURE("Companions.Expeditions", "동료 파견", "Companions", "Character", "Foundation.Persistence,Combat.Rulesets")
PROJECTJ_FEATURE("Companions.PetBattles", "펫 대전", "Companions", "Character", "Foundation.Persistence,Combat.Rulesets")
PROJECTJ_FEATURE("Community.Chat", "지역·파티·길드 채팅", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.Voice", "음성 서비스 연결", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.LookingForGroup", "파티 찾기", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.Calendar", "행사·일정", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.Bulletin", "게시판", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.Minigames", "미니게임", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.Racing", "경주", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.Cards", "카드·보드게임", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.Performance", "공연·합주", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.UserEvents", "유저 행사", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("Community.Reports", "신고·증거 참조", "Community", "Account", "Social.Blocklist,Foundation.Transport")
PROJECTJ_FEATURE("LiveOps.Calendar", "운영 일정", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.SeasonPass", "시즌 패스", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events,Economy.RewardClaims")
PROJECTJ_FEATURE("LiveOps.Attendance", "출석·접속 보상", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.DailyWeekly", "일간·주간 리셋", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.Holiday", "축제·기간 이벤트", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.WorldGoals", "서버 누적 목표", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.FeatureFlags", "기능 개방·점진 적용", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.Compensation", "장애 보상", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.Campaigns", "캠페인·프로모션", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.ContentVersion", "정의 데이터 버전", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("LiveOps.Leaderboards", "랭킹 집계", "LiveOps", "Service", "Foundation.Clock,Foundation.Persistence,Foundation.Events")
PROJECTJ_FEATURE("Platform.Authentication", "인증 서비스 연결", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.ServerDirectory", "서버 검색", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.Admission", "접속 대기·수용량", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.Reconnect", "재접속 복구", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.Presence", "온라인 상태", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.Routing", "샤드·지역 라우팅", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.Transfer", "캐릭터 이전", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.Maintenance", "점검·드레인", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.Localization", "지역화 계약", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Platform.Accessibility", "접근성 설정", "Platform", "Service", "Foundation.Transport,Foundation.Access")
PROJECTJ_FEATURE("Operations.Audit", "상태 변경 감사", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.Metrics", "처리량·지연 계측", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.Tracing", "요청 상관 추적", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.Moderation", "제재·차단", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.Support", "고객 지원 도구", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.Recovery", "복구·재처리", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.Migration", "스키마 마이그레이션", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.AbuseLimits", "요청·경제 악용 제한", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.ConfigValidation", "설정 검증", "Operations", "Service", "Foundation.Observability,Foundation.Access")
PROJECTJ_FEATURE("Operations.DataExport", "운영 데이터 내보내기", "Operations", "Service", "Foundation.Observability,Foundation.Access")
